project:
  type: book
  output-dir: _book

engine: knitr

book:
  title: "ggplot2: Elegant Graphics for Data Analysis (3e)"
  reader-mode: true

  page-footer:
    left: |
      ggplot2: Elegant Graphics for Data Analysis (3e) was written by
      Hadley Wickham, Danielle Navarro, and Thomas Lin Pedersen.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://ggplot2-book.org/
  repo-url: https://github.com/hadley/ggplot2-book/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - preface-3e.qmd
    - preface-2e.qmd

    - part: start.qmd
      chapters:
        - introduction.qmd
        - getting-started.qmd

    - part: extending.qmd
      chapters:
        - programming.qmd
        - internals.qmd
        - extensions.qmd
        - ext-springs.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    code-link: true

    author-meta: "Hadley Wickham, Danielle Navarro, and Thomas Lin Pedersen"
    include-in-header: "ga_script.html"
    callout-appearance: simple

  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm

editor: visual

